const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#0A4FFF",
    background: "#FBFCFE",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#0A4FFF",
    primary20: "rgba(10, 79, 255, 0.14)",
    primaryForeground: "#FFFFFF",
    secondary: "#FF8C42",
    secondaryForeground: "#FFFFFF",
    muted: "#F3F5FA",
    mutedForeground: "#7D889B",
    accent: "#EEF2FF",
    accentForeground: "#0A4FFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    success: "#2ECC71",
    successForeground: "#FFFFFF",
    border: "#E8EDF5",
    input: "#E8EDF5",
    shadow: "rgba(16, 24, 40, 0.08)",
    orangeColor: "#FF8C42",
    mtnColor: "#FFCC00",
    moovColor: "#0055B3",
  },
  radius: 16,
};

export default colors;
